

CREATE TABLE pre_users(
	token VARCHAR(32) PRIMARY KEY,
	user_id VARCHAR(16) NOT NULL,
	mail VARCHAR(254) UNIQUE,
	user_name NVARCHAR(25) NOT NULL,
	pw VARCHAR(512) NOT NULL,
	comment NVARCHAR(300) DEFAULT '',
	user_icon VARCHAR(32) NULL,
	rgdt DATETIME DEFAULT dbo.GET_TOKYO_DATETIME(),
	updt DATETIME DEFAULT dbo.GET_TOKYO_DATETIME()
);

