-- ルーム

CREATE TABLE rooms(
	room_id VARCHAR(32) PRIMARY KEY,
	room_name VARCHAR(30) NOT NULL,
	room_icon VARCHAR(32) NULL,
	explanation VARCHAR(100) NULL,
	pw VARCHAR(16) NULL,
	is_public BIT NOT NULL,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);


