-- セッション管理

CREATE TABLE sessions(
	session_id VARCHAR(32) PRIMARY KEY,
	user_id VARCHAR(16) NULL,
	is_valid BIT DEFAULT 1,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fgk_user_session FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE CASCADE ON UPDATE CASCADE
);


