-- ユーザ情報

CREATE TABLE users(
	user_id VARCHAR(16) PRIMARY KEY,
	mail VARCHAR(254) UNIQUE,
	pw VARCHAR(512) NOT NULL,
	comment NVARCHAR(300) DEFAULT '',
	user_icon VARCHAR(32) NULL,
	pw_changed DATETIME DEFAULT CURRENT_TIMESTAMP,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);

