-- ルームとユーザの関連

CREATE TABLE room_user(
	room_id VARCHAR(32),
	user_id VARCHAR(254),
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(room_id, user_id)
);

