-- セッション管理

CREATE TABLE session(
	session_id VARCHAR(32) PRIMARY KEY,
	user_id VARCHAR(254) NULL,
	valid BIT DEFAULT 1,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
);


