-- ユーザ情報

CREATE TABLE user(
	user_id VARCHAR(254) PRIMARY KEY,
	pw VARCHAR(512) NOT NULL,
	user_name NVARCHAR(50) NOT NULL,
	comment NVARCHAR(300) DEFAULT '',
	user_icon VARCHAR(32) NULL,
	pw_changed DATETIME DEFAULT CURRENT_TIMESTAMP,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP
);

