-- クイズ所有者

CREATE TABLE user(
	mail VARCHAR(200) PRIMARY KEY,
	pw VARCHAR(512) NOT NULL,
	user_name NVARCHAR(50) NOT NULL,
	pw_changed DATETIME DEFAULT CURRENT_TIMESTAMP,
	rgdt DATETIME DEFAULT CURRENT_TIMESTAMP,
	updt DATETIME DEFAULT CURRENT_TIMESTAMP,
);

-- /cookie/set
